version: '3'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
      - .local.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    env_file:
      - .env
      - .local.env
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    restart: always
    ports:
      - 8181:80

  cdn:
    image: nginx:alpine
    env_file:
      - .env
      - .local.env
    ports:
      - "80:80"
    volumes:
      - ${UPLOAD_FOLDER}:/usr/share/nginx/html/
      - ./cdn-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db

volumes:
  dbdata: