version: '3'

services:

  db:
    image: mysql:latest
    env_file:
      - .env
      - .local.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
      - .local.env
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
    restart: always
    ports:
      - 8181:80

  app:
    build: .
    env_file:
      - .env
      - .local.env
    ports:
      - "8080:8080"
    volumes:
      - ${UPLOAD_FOLDER}:/uploads
    depends_on:
      - db

  cdn:
    build: nginx:alpine
    env_file:
      - .env
      - .local.env
    ports:
      - "81:80"
    volumes:
      - ${UPLOAD_FOLDER}:/usr/share/nginx/html/
      - cdn-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db

volumes:
  dbdata:
  