version: '3'

services:

  db:
    image: mysql:latest
    env_file:
      - .env
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
    restart: always
    ports:
      - 8181:80
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ${UPLOAD_FOLDER}:/uploads
    depends_on:
      - db
  cdn:
    build: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ${UPLOADS_PATH}:/usr/share/nginx/html/
      - cdn-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db

volumes:
  dbdata:
  